name: website Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build the lovesh's React Application
      run: npm run build

    - name: Deploy to loveshgoyal branch
      run: |
        git config --global user.email "loveshgoyal2002@gmail.com"
        git config --global user.name "lovesh1711"
        git checkout --orphan loveshgoyal
        ls
        rm -rf node_modules
        ls
        rm -rf public
        ls
        rm -rf src
        ls
        git add -f build
        cp -r build/. .
        rm -rf build
        rm -rf .github
        rm -rf package-lock.json
        rm -rf package.json
        git add .
        git commit -m "lovesh push"
        git push --force origin loveshgoyal

